Syslog rate limit configuration support
Junchao-Mellanox/sonic-buildimage pull request #153
Opened 2022-10-11 07:09 UTC by Junchao-Mellanox

#### Why I did it

#### How I did it

#### How to verify it

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205

#### Description for the changelog

#### Ensure to add label/tag for the feature raised. example - [PR#2174](https://github.com/sonic-net/sonic-utilities/pull/2174) where, Generic Config and Update feature has been labelled as GCU.

#### Link to config_db schema for YANG module changes

#### A picture of a cute animal (not mandatory but encouraged)

2022-10-12 03:19 UTC, Junchao-Mellanox commented on rules/functions
> +    $(eval export customized_rate_limit=$($(1).gz_CUSTOMIZED_RATE_LIMIT))
remove this line

2022-10-12 03:19 UTC, Junchao-Mellanox commented on src/sonic-containercfgd/containercfgd/containercfgd.py
> +                interval = match.group(1)
do we need break early?

2022-10-12 03:19 UTC, Junchao-Mellanox commented on src/sonic-containercfgd/containercfgd/containercfgd.py
> +    RestartWaiter.waitRestartDone()
rename to waitAdvancedBootDone()

2022-10-12 03:19 UTC, Junchao-Mellanox commented on src/sonic-containercfgd/containercfgd/containercfgd.py
> +    container_name = os.environ['CONTAINER_NAME']
check if CONTAINER_NAME is set

2022-10-12 03:19 UTC, Junchao-Mellanox commented on src/sonic-yang-models/yang-models/sonic-feature.yang
> +                leaf has_customized_syslog_rate_limit {
remove this

2022-10-13 06:03 UTC, keboliu commented on src/sonic-containercfgd/containercfgd/containercfgd.py
> +    def parse_syslog_conf(self):
Is it possible to reuse the code from host side?

2022-10-18 01:53 UTC, Junchao-Mellanox commented on src/sonic-containercfgd/containercfgd/containercfgd.py
> +                return
no, each container may receive notification for other containers.

2022-10-21 08:26 UTC, Junchao-Mellanox commented on src/sonic-containercfgd/containercfgd/containercfgd.py
> +    def parse_syslog_conf(self):
It would be hard to do so, the logic here is not general enough to put into common utilities code

2022-10-24 14:29 UTC, nazariig commented
@Junchao-Mellanox please update your local `master` to facilitate code review

2022-10-24 22:16 UTC, nazariig requested changes

2022-10-24 22:16 UTC, nazariig commented on src/sonic-containercfgd/containercfgd/containercfgd.py
> +        if new_interval == cur_interval and new_burst == cur_burst:
@Junchao-Mellanox can we have some logging here?

2022-10-25 01:33 UTC, Junchao-Mellanox commented
re-create one: https://github.com/Junchao-Mellanox/sonic-buildimage/pull/155

2022-10-25 01:45 UTC, Junchao-Mellanox commented on files/build_templates/docker_image_ctl.j2
> +        if [ "$CONTAINER_EXISTS" = "yes" ]; then
For multi ASIC platform, I am not sure that `TARGET_IP=$(docker network inspect bridge --format={{ "'{{(index .IPAM.Config 0).Gateway}}'" }})` always return the same value.

2022-10-25 02:04 UTC, Junchao-Mellanox commented on src/sonic-containercfgd/containercfgd/containercfgd.py
> +        run_command("supervisorctl restart rsyslogd")
what do you mean by reset?

2022-10-25 12:03 UTC, nazariig approved these changes

2022-10-25 14:28 UTC, closed without merging