Enable runtime config log level
Junchao-Mellanox/sonic-buildimage pull request #228
Opened 2024-06-11 02:52 UTC by Junchao-Mellanox

#### Why I did it

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it

#### How to verify it

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ] 

#### Description for the changelog

#### Link to config_db schema for YANG module changes

#### A picture of a cute animal (not mandatory but encouraged)

2024-06-26 06:05 UTC, prgeor reviewed
@Junchao-Mellanox can we agree on the HLD first before implementation?

2024-06-27 16:30 UTC, prgeor requested changes
@Junchao-Mellanox Please use singleton class for SysLogger that way each process will have access to this singleton class and you can update the log level on receiving the signal.

2024-07-17 04:12 UTC, Junchao-Mellanox commented
ci passed 4246

2024-07-18 02:53 UTC, keboliu approved these changes

2024-07-18 02:54 UTC, closed without merging